# -*- coding: utf-8 -*-
"""EJERCICIO3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vasJjWqdsbxkZst0-PwN1IBgIkjyJ6r0
"""

import numpy as np
import matplotlib.pyplot as plt

# Definimos la función a integrar
def f(x):
    return np.sin(x)

# Implementación de la regla del trapecio
def trapezoidal_rule(a, b, n):
    x = np.linspace(a, b, n+1)  # Puntos equidistantes
    y = f(x)
    h = (b - a) / n
    integral = (h / 2) * (y[0] + 2 * sum(y[1:n]) + y[n])  # Regla del trapecio compuesta
    return integral, x, y

# Parámetros de integración
a, b = 0, np.pi  # Intervalo de integración
n_values = [4, 8, 16]  # Diferentes valores de subdivisiones

for n in n_values:
    integral_approx, x_vals, y_vals = trapezoidal_rule(a, b, n)
    print(f"Integral aproximada con n={n}: {integral_approx:.6f}")

    # Crear una nueva figura para cada n
    plt.figure(figsize=(8, 5))

    # Gráfica de la función original
    x_fine = np.linspace(a, b, 100)
    y_fine = f(x_fine)
    plt.plot(x_fine, y_fine, 'r-', label=r'$f(x) = \sin(x)$', linewidth=2)

    # Gráfica de la aproximación con trapecios
    plt.fill_between(x_vals, y_vals, alpha=0.3, color='blue', label="Aproximación Trapecios")
    plt.plot(x_vals, y_vals, 'bo-', label="Puntos de integración")

    # Etiquetas y leyenda
    plt.xlabel("$x$")
    plt.ylabel("$f(x)$")
    plt.title(f"Aproximación con la regla del trapecio (n={n})")
    plt.legend()
    plt.grid()

    # Guardar la figura con un nombre específico para cada n
    plt.savefig(f"trapecio_sin_n{n}.png")
    plt.show()